pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
    - name: git
      image: alpine/git
      command:
        - sleep
      args:
        - 99d
"""
    }
  }

  environment {
    ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    IMAGE_NAME   = "${ECR_REPOSITORY_NAME}"
    IMAGE_TAG    = "v1.0.${BUILD_NUMBER}"
    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"
    GITHUB_USERNAME = "${GITHUB_USERNAME}"
    GITHUB_REPO = "${GITHUB_REPO}"
    GITHUB_BRANCH = "${GITHUB_BRANCH}"
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \\
              --context `pwd`/django \\
              --dockerfile Dockerfile \\
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \\
              --cache=true \\
              --insecure \\
              --skip-tls-verify
          '''
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              git config --global --add safe.directory '*'
              git clone https://$GIT_USERNAME:$GIT_PAT@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git
              git checkout $GITHUB_BRANCH

              git remote set-url origin https://$GIT_USERNAME:$GIT_PAT@github.com/$GITHUB_USERNAME/$GITHUB_REPO.git


              echo "--- LISTING REPO CONTENT ---"
              ls -R charts
              echo "----------------------------"

              cd charts/django-app

              sed -i "s/tag: .*/tag: $IMAGE_TAG/" values.yaml
              sed -i "s|repository: .*|repository: $ECR_REGISTRY/$IMAGE_NAME|" values.yaml

              git config user.email "$COMMIT_EMAIL"
              git config user.name "$COMMIT_NAME"

              git add values.yaml
              git commit -m "Update image tag to $IMAGE_TAG"
              git push origin $GITHUB_BRANCH
            '''
          }
        }
      }
    }
  }
}
